### ISSUE TITLE
Any demo available?

### ISSUE THREAD

**Issue by kaphleamrit2** [Sakib1263/TF-1D-2D-Segmentation-End2EndPipelines#1]
Is any demo available soon? It would be great if you could provide the implementation details.

Thanks.

**Comment by Sakib1263** [comment]
I have added one demo pipeline in the following link. If you have any more concerns, please reply here. If you find the repo helpful, put a star and share with others who might need it for their projects.

https://github.com/Sakib1263/1D-2D-Segmentation-AutoEncoder-TF2-KERAS/tree/main/Codes/1DCNN/Pipeline


Regards,
Sakib
